// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPdKCKmGkDgCmXUKDIiZI-GlxDTwQOUW4',
    appId: '1:170362459388:web:8063511f5fdfd394c63379',
    messagingSenderId: '170362459388',
    projectId: 'fir-tutorial-6c786',
    authDomain: 'fir-tutorial-6c786.firebaseapp.com',
    storageBucket: 'fir-tutorial-6c786.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhYJfV56Wmk8kw1UaIzvS9gFg4ft2mzNQ',
    appId: '1:170362459388:android:32b180e010d1fdb5c63379',
    messagingSenderId: '170362459388',
    projectId: 'fir-tutorial-6c786',
    storageBucket: 'fir-tutorial-6c786.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCamT_JYfkB5wFiop36n5WtdrHjUxQdERQ',
    appId: '1:170362459388:ios:090e188e601e1e21c63379',
    messagingSenderId: '170362459388',
    projectId: 'fir-tutorial-6c786',
    storageBucket: 'fir-tutorial-6c786.appspot.com',
    iosBundleId: 'com.example.firebasetutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCamT_JYfkB5wFiop36n5WtdrHjUxQdERQ',
    appId: '1:170362459388:ios:7dc90ab29413931fc63379',
    messagingSenderId: '170362459388',
    projectId: 'fir-tutorial-6c786',
    storageBucket: 'fir-tutorial-6c786.appspot.com',
    iosBundleId: 'com.example.firebasetutorial.RunnerTests',
  );
}
